name: PlayTime
version: 0.0.1
main: com.github.sxnsh1ness.playtime.PlayTimePlugin
api-version: '1.21'
author: Sxnsh1ne
description: Standalone PlayTime Tracking Plugin
softdepend:
  - PlaceholderAPI
commands:
  playtime:
    description: Shows player playtime.
    usage: /playtime [player]
